# This workflow runs spell_check test for Ameba Arduino SDK

name: Check word spell
on: [push, pull_request]
#  workflow_dispatch:
jobs:
  spell-check:
    name: Run spell-check check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'source'
    steps:
    - name: Checkout repository # and submodules
      uses: actions/checkout@v4
#      with:
#        submodules: recursive
    - name: Run spell-check for multi-floders
#      uses: codespell-project/actions-codespell@master
      uses: codespell-project/actions-codespell@v2
      with:
        skip: source/_download/Education/NTNU/台日友好課程PPT_EngVer.pdf,source/_download/Education/NTNU/台日友好課程PPT_JPVer.pdf
        ignore_words_list: ameba,datas
#        ignore_words_file: .codespellignore
        path: ${{ matrix.path }}
